export default {
  register: 'POST /register',
  sigil: 'POST /sigil',
  init: 'POST /agent/init',
  heartbeat: 'POST /agent/heartbeat',
  'reissue-proof': 'POST /agent/reissue-proof',
  spawn: 'POST /agent/spawn',
  'beat-status': 'GET /agent/beat-status/:hash',
  status: 'GET /status/:hash',
  verify: 'GET /verify/:hash',
  anchor: 'GET /beat/anchor',
  'fees-summary': 'GET /fees/summary',
  'authority-key': 'GET /.well-known/authority',
  '---': { type: 'separator' },
  checkin: 'POST /agent/checkin (Deprecated)',
  resync: 'POST /agent/resync (Deprecated)',
}
